backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Confirmation_Cause_Code__c</fullName>
        <label>Confirmation Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Closed</fullName>
                </value>
                <value>
                    <fullName>Account Handover/Debt Review</fullName>
                </value>
                <value>
                    <fullName>Action Required From Client</fullName>
                </value>
                <value>
                    <fullName>Bank Details Already Updated</fullName>
                </value>
                <value>
                    <fullName>Cash payer customer</fullName>
                </value>
                <value>
                    <fullName>Client Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Client Not Interested</fullName>
                </value>
                <value>
                    <fullName>Client to Contact DOI</fullName>
                </value>
                <value>
                    <fullName>Confirmation via SMS Required</fullName>
                </value>
                <value>
                    <fullName>Debit Order/Policy Cancelled</fullName>
                </value>
                <value>
                    <fullName>Details Not Found/Invalid Details</fullName>
                </value>
                <value>
                    <fullName>No active debit orders</fullName>
                </value>
                <value>
                    <fullName>Paid up</fullName>
                </value>
                <value>
                    <fullName>Policy lapsed/frozen</fullName>
                </value>
                <value>
                    <fullName>Successfully Confirmed</fullName>
                </value>
                <value>
                    <fullName>Confirmation via email required</fullName>
                    <isActive>false</isActive>
                    <label>Confirmation via email required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Capitec_ConversionVerifyDebitOrders.cls
/**
 * @description       : COCONV-1938 - Invocable Method to check if all Debit Orders related to a case has a response
 * @author            : Samiirah.A@bsky.co.za
 * @group             : Capitec Conversions
 * @last modified on  : 09-04-2025
 * @last modified by  : Samiirah.A@bsky.co.za
**/
public with sharing class Capitec_ConversionVerifyDebitOrders {

    public class requestWrapper {
        @InvocableVariable(required=true)
        public Id caseId;
    }

    public class responseWrapper {
        @InvocableVariable
        public Boolean result;
    }

    @InvocableMethod(label='Analyse Debit Orders')
    public static List<responseWrapper> analyseDebitOrders(List<requestWrapper> caseWrappers) {
        Boolean autoCloseCase = true;

        Set<Id> setCaseIds = new Set<Id>();
        List<Case> lstCaseToUpdate = new List<Case>();
        Map<Id, List<Debit_Order__c>> mapCaseIdToDOs = new Map<Id, List<Debit_Order__c>>();

        for (requestWrapper wrapper : caseWrappers) {
            if (wrapper.caseId != null) {
                setCaseIds.add(wrapper.caseId);
            }
        }

        System.debug('##setCaseIds :' +setCaseIds);

        if (!setCaseIds.isEmpty()) {
            mapCaseIdToDOs = getDebitOrders(setCaseIds);

             System.debug('##mapCaseIdToDOs :' +mapCaseIdToDOs);

            for (Id caseId : mapCaseIdToDOs.keySet()) { //Case record will always be one, therefore no complexity due to nested for loop
                
                //one debit order - Close case
                if (mapCaseIdToDOs.get(caseId).size() <= 1){
                    autoCloseCase = true;
                }

                for (Debit_Order__c debitOrder : mapCaseIdToDOs.get(caseId)) {
                    if (debitOrder.Confirmation_Cause_Code__c == null) {
                        autoCloseCase = false;
                    }
                }
               
            }
            System.debug('##autoCloseCase :' +autoCloseCase);
        }

        responseWrapper response = new responseWrapper();
        response.result = autoCloseCase;

        return new List<responseWrapper> {response};
    }



    public static Map<Id,List<Debit_Order__c>> getDebitOrders(Set<Id> setIds){
        Map<Id,List<Debit_Order__c>> mapCaseIdToDOs = new Map<Id, List<Debit_Order__c>>();

        for(Debit_Order__c debitOrder : [SELECT Id, 
                                                Confirmation_Cause_Code__c, 
                                                Case__c 
                                         FROM Debit_Order__c 
                                         WHERE Case__c IN:setIds]){
            if(mapCaseIdToDOs.containsKey(debitOrder.Case__c)){
                mapCaseIdToDOs.get(debitOrder.Case__c).add(debitOrder);
            }
            else{
                mapCaseIdToDOs.put(debitOrder.Case__c, new List<Debit_Order__c>{debitOrder});
            }
        }

        return mapCaseIdToDOs;
    }

    
}