backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case_Closure_Reason__c</fullName>
        <label>Case Closure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch indicate - Ignore request</fullName>
                </value>
                <value>
                    <fullName>Client Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>Client Did not agree to switch</fullName>
                </value>
                <value>
                    <fullName>Client will submit</fullName>
                </value>
                <value>
                    <fullName>Invalid - Agreement not setup</fullName>
                </value>
                <value>
                    <fullName>Invalid - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Invalid - No active debit orders</fullName>
                </value>
                <value>
                    <fullName>Invalid - Request for Savings Plan</fullName>
                </value>
                <value>
                    <fullName>Invalid Bank Statement Request</fullName>
                </value>
                <value>
                    <fullName>Invalid Payslip Request – Invalid Reference number/No Amount</fullName>
                </value>
                <value>
                    <fullName>Invalid Payslip Request – No Payslip attached</fullName>
                </value>
                <value>
                    <fullName>Invalid Request - Bank Statement Older than 3 months</fullName>
                </value>
                <value>
                    <fullName>Invalid SMS Request – Incomplete or Invalid Reference/no amount</fullName>
                </value>
                <value>
                    <fullName>Missing Bank Statement/No Comments</fullName>
                </value>
                <value>
                    <fullName>Refund Processed</fullName>
                </value>
                <value>
                    <fullName>No attachment/invalid attachment</fullName>
                </value>
                <value>
                    <fullName>Query not related to switch</fullName>
                </value>
                <value>
                    <fullName>Auto Close</fullName>
                </value>
                <value>
                    <fullName>Auto Close - No Client feedback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DO_Issue__c</fullName>
        <label>DO Issue</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference number unclear</fullName>
                </value>
                <value>
                    <fullName>Incomplete reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid Reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid or incomplete debit order info</fullName>
                </value>
                <value>
                    <fullName>No amount provided</fullName>
                </value>
                <value>
                    <fullName>Client unreachable/ no response</fullName>
                </value>
                <value>
                    <fullName>Requested Debit order does not reflect on the statement</fullName>
                </value>
                <value>
                    <fullName>DOA missing</fullName>
                </value>
                <value>
                    <fullName>DOA invalid</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CB To Email</fullName>
                </value>
                <value>
                    <fullName>CB to Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Client to Switch</fullName>
                </value>
                <value>
                    <fullName>MFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Conversions_EmailTemplatesControllerTest.cls
/**
 * @description       : Test class for Conversions_EmailTemplatesController.cls
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 01-27-2026
 * @last modified by  : Samiirah Aujub
**/
@isTest
public with sharing class Conversions_EmailTemplatesControllerTest {
    public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();


    @testSetup
    static void setupTestData() {

        Account acc = new Account(Name = 'Test Account',
                                  CIF_Number__c = '12345678');
        insert acc;

        Case testCase = new Case(Subject = 'Test Case',
                                 Status = 'In Progress',
                                 Origin = 'Branch',
                                 AccountId = acc.Id,
                                 RecordTypeId = CONVERSIONS_RECORDID
                                );
        insert testCase;

        Conversion__c conversion = new Conversion__c(
                Case__c = testCase.Id,
                Case_Closure_Reason__c = 'Auto Close'
            );
            insert conversion;

        Debit_Order_Initiator__c initiator = new Debit_Order_Initiator__c(Name = 'Test Initiator',
                                                                          Preferred_Comms__c = 'CB To Email'
                                                                         );
        insert initiator;

        Debit_Order__c debitOrder = new Debit_Order__c(Name = 'DO-001',
                                                       Amount__c = 100.0,
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_Order_Initiator__c = initiator.Id,
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       DO_Issue__c = 'DOA invalid',
                                                       Case__c = testCase.Id
        );
        insert debitOrder;
    }


    @isTest
    static void testControllerMethods() {

        Case caseRecord = [SELECT Id FROM Case LIMIT 1];

        Conversions_EmailTemplatesController controller =new Conversions_EmailTemplatesController();
        controller.caseRecordId = caseRecord.Id;

        Case returnedCase = controller.getCaseRecord();
        Conversion__c returnedConv = controller.getConversion();

        System.assertNotEquals(null, returnedCase, 'Case should be returned');
        System.assertEquals(caseRecord.Id, returnedCase.Id, 'Case ID should match');
        System.assertNotEquals(null, returnedConv, 'Conversion record should be returned');
    }


    @isTest
    static void testNoCaseId() {
        Conversions_EmailTemplatesController controller =new Conversions_EmailTemplatesController();

        System.assertEquals(null, controller.getCaseRecord(), 'Case should be null');
        System.assertEquals(null, controller.getConversion(), 'Conversion should be null');
    }

    @isTest
    static void testDebitOrdersWithIssues() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Account acc = [SELECT Id FROM Account LIMIT 1];


        Conversions_EmailTemplatesController controller = new Conversions_EmailTemplatesController();
        controller.caseRecordId = testCase.Id;

        Boolean hasIssues = controller.getHasIssues();
        List<String> issueLines = controller.getDebitOrderIssueLines();

        System.assertEquals(true, hasIssues, 'Case should have debit order issues');
        System.assertEquals(1, issueLines.size(), 'One issue line expected');
    }

}