backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Conversions_ConfirmationController_Test.cls
/**
 * @description       : Test class for Conversions_ConfirmationController
 * @author            : Samiirah Aujub
 * @group             : 
 * @last modified on  : 02-06-2026
 * @last modified by  : Samiirah Aujub
**/
@IsTest
public with sharing class Conversions_ConfirmationController_Test {
public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();

    @testSetup
    static void setupTestData() {
        Case testCase = new Case(Subject = 'Test Case',
                                 Status = 'In Progress',
                                 Origin = 'Branch',
                                 Claim_Number__c = '12345679',
                                 RecordTypeId = CONVERSIONS_RECORDID
                                );
        insert testCase;

        Conversion__c conversion = new Conversion__c(Case__c = testCase.Id,
                                                     Old_Account_Number__c = '111222333'
                                                     );
        insert conversion;
    }

    @IsTest
    static void testGetCaseInfo() {
        Case caseRecord = [SELECT Id FROM Case LIMIT 1];
    
        Test.startTest();
            Case result = Conversions_ConfirmationController.getCaseInfo(caseRecord.Id);
        Test.stopTest();

    }

    @IsTest
    static void testGetCaseInfoError() {
        Id fakeCaseId = '500000000000000AAA';

        Test.startTest();
            Case result = Conversions_ConfirmationController.getCaseInfo(fakeCaseId);
        Test.stopTest();

        System.assertEquals(null, result,'Method should return null when case does not exist');
    }


    @IsTest
    static void testReturnCaseToAwaitingDoi() {
        Case caseRecord = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
            Boolean result = Conversions_ConfirmationController.returnCaseToAwaitingDoi(caseRecord.Id);
        Test.stopTest();

        System.assertEquals(true, result, 'Expected true on successful update');
    }

        @IsTest
    static void testReturnCaseToAwaitingDoiError() {
        Id fakeCaseId = '500000000000000AAA';

        Test.startTest();
            Boolean result = Conversions_ConfirmationController.returnCaseToAwaitingDoi(fakeCaseId);
        Test.stopTest();

        System.assertEquals(false, result,'Method should return null when case does not exist');
    }


}