backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Terminated</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Allocated Assessing</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Response</fullName>
                </value>
                <value>
                    <fullName>Awaiting External Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting for Internal Department Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Insurer Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Medical Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting OCI Insurer</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Adverse Media</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Reported</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Review Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Review Not Required</fullName>
                </value>
                <value>
                    <fullName>Claims Forum</fullName>
                </value>
                <value>
                    <fullName>Claims Management</fullName>
                </value>
                <value>
                    <fullName>Contact Client</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Declined (Closed)</fullName>
                </value>
                <value>
                    <fullName>Documents not received</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>EDD Requirements Failed</fullName>
                </value>
                <value>
                    <fullName>Escalated - Mandate approval</fullName>
                </value>
                <value>
                    <fullName>Evaluating Client Response</fullName>
                </value>
                <value>
                    <fullName>Finalised</fullName>
                </value>
                <value>
                    <fullName>Final Termination Notice Sent</fullName>
                </value>
                <value>
                    <fullName>Guardrisk Assessing</fullName>
                </value>
                <value>
                    <fullName>HB 48hrs SMS notice</fullName>
                    <label>Hard Block 48hrs SMS notice</label>
                </value>
                <value>
                    <fullName>Hard Block Applied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion_Comms__e.object
<CustomObject>
    <description>Platform Event to send Conversion related Comms</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Conversion Comms</label>
    <pluralLabel>Conversion Comms</pluralLabel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FD Debit Order Switch</fullName>
                </value>
                <value>
                    <fullName>WS debit Order Switch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Confirmation_Cause_Code__c</fullName>
        <label>Confirmation Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Closed</fullName>
                </value>
                <value>
                    <fullName>Account Handover/Debt Review</fullName>
                </value>
                <value>
                    <fullName>Action Required From Client</fullName>
                </value>
                <value>
                    <fullName>Bank Details Already Updated</fullName>
                </value>
                <value>
                    <fullName>Cash payer customer</fullName>
                </value>
                <value>
                    <fullName>Client Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Client Not Interested</fullName>
                </value>
                <value>
                    <fullName>Client to Contact DOI</fullName>
                </value>
                <value>
                    <fullName>Confirmation via SMS Required</fullName>
                </value>
                <value>
                    <fullName>Debit Order/Policy Cancelled</fullName>
                </value>
                <value>
                    <fullName>Details Not Found/Invalid Details</fullName>
                </value>
                <value>
                    <fullName>No active debit orders</fullName>
                </value>
                <value>
                    <fullName>Paid up</fullName>
                </value>
                <value>
                    <fullName>Policy lapsed/frozen</fullName>
                </value>
                <value>
                    <fullName>Successfully Confirmed</fullName>
                </value>
                <value>
                    <fullName>Confirmation via email required</fullName>
                    <isActive>false</isActive>
                    <label>Confirmation via email required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOI_Sub_Name__c</fullName>
        <label>DOI Sub Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DO_Issue__c</fullName>
        <label>DO Issue</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference number unclear</fullName>
                </value>
                <value>
                    <fullName>Incomplete reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid Reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid or incomplete debit order info</fullName>
                </value>
                <value>
                    <fullName>No amount provided</fullName>
                </value>
                <value>
                    <fullName>Client unreachable/ no response</fullName>
                </value>
                <value>
                    <fullName>Requested Debit order does not reflect on the statement</fullName>
                </value>
                <value>
                    <fullName>DOA missing</fullName>
                </value>
                <value>
                    <fullName>DOA invalid</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Account_Formula__c</fullName>
        <formula>Case__r.Conversion__r.Old_Account_Number__c</formula>
        <label>From Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_yet_onboarded__c</fullName>
        <label>DOI not Onboarded</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Withdrawn_Cause_Code__c</fullName>
        <label>Withdrawn Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agent Capturing Error</fullName>
                </value>
                <value>
                    <fullName>Branch advised to ignore request</fullName>
                </value>
                <value>
                    <fullName>Client cancelled request</fullName>
                </value>
                <value>
                    <fullName>Client requested to switch for next month</fullName>
                </value>
                <value>
                    <fullName>Employer does not accept Capitec Banking details</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <fields>
        <fullName>DOI_Contact_Email__c</fullName>
        <label>DOI Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CB To Email</fullName>
                </value>
                <value>
                    <fullName>CB to Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Client to Switch</fullName>
                </value>
                <value>
                    <fullName>MFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Capitec_DebitOrderController.cls
/**
 * @description       : Apex controller for Capitec_ConversionsDebitOrders LWC
 * @author            : Samiirah.A@bsky.co.za
 * @group             : Capitec Conversions
 * @last modified on  : 03-24-2026
 * @last modified by  : Samiirah Aujub
**/
public with sharing class Capitec_DebitOrderController {

    private static final String API_USER = 'API ';

    public class CaseWrapper {
        @AuraEnabled public Case caseRecord;
        @AuraEnabled public Boolean manualCase;
    }

    @AuraEnabled(cacheable=true)
    public static List<Debit_Order__c> getDebitOrders(Id caseId) {
        return [SELECT Id, 
                       Name, 
                       Amount__c,
                       From_Account_Formula__c,
                       Category__c,
                       Submission_Date__c,
                       To_Capitec_Account__c,
                       Debit_Order_Initiator__c,
                       Debit_Order_Initiator__r.Name,
                       Debit_Order_Initiator__r.Preferred_Comms__c,
                       Debit_Order_Initiator__r.DOI_Contact_Email__c,
                       Debit_OrderDate__c,
                       Confirmation_Cause_Code__c,
                       Submitted_Cause_Code__c,
                       Withdrawn_Cause_Code__c,
                       DOI_Sub_Name__c,
                       DO_Issue__c,
                       Reviewed__c,
                       Preferred_Comms__c,
                       Not_yet_onboarded__c
                FROM Debit_Order__c 
                WHERE Case__c = :caseId];
    }

    @AuraEnabled(cacheable=true)
    public static CaseWrapper getCaseInfo(Id caseId) {
        Case caseRec = [SELECT  Id, 
                                Subject,
                                CaseNumber, 
                                Status,
                                Sub_Status__c,
                                Capitec_Category__c,
                                Origin,
                                Account.Name,
                                Account.PersonEmail,
                                Account.PersonContactId,
                                Conversion__r.Old_Account_Number__c,
                                Conversion__r.Manual_Case__c
                        FROM Case 
                        WHERE Id = :caseId
                        LIMIT 1];

        CaseWrapper caseWrapper = new CaseWrapper();
        caseWrapper.caseRecord = caseRec;
        caseWrapper.manualCase = caseRec.Conversion__r.Manual_Case__c;

        return caseWrapper;
    }
    
    @AuraEnabled(cacheable=true)
    public static Conversion__c getConversionRecord(Id caseId) {
        return [SELECT Id,
                       Old_Account_Number__c
                FROM Conversion__c 
                WHERE Case__c = :caseId];
    }


    /*

    @AuraEnabled(cacheable=true)
    public static Debit_Order_Initiator__c getDOIDetails(Id doiId) {
        List<Debit_Order_Initiator__c> lstDOIs = [ SELECT Id, 
                                                          Preferred_Comms__c,
                                                          DOI_Contact_Email__c
                                                   FROM Debit_Order_Initiator__c 
                                                   WHERE Id = :doiId 
                                                   LIMIT 1];
        if (!lstDOIs.isEmpty()) {
            return lstDOIs[0];
        }
        return null;
    }*/

    
    @AuraEnabled(cacheable=true)
    public static List<Debit_Order_Initiator__c> searchDOI(String searchKey) {
        String likeKey = '%' + searchKey + '%';

        List<Debit_Order_Initiator__c> lstDOIs = [ SELECT Id, 
                                                          Name,
                                                          Preferred_Comms__c,
                                                          DOI_Contact_Email__c
                                                   FROM Debit_Order_Initiator__c 
                                                   WHERE Name LIKE :likeKey
                                                   LIMIT 10];
        if (!lstDOIs.isEmpty()) {
            return lstDOIs;
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static  List<String> getHolidays() {
        List<String> lstHolidays = new List<String>();

        for(Holiday holiday : [SELECT Id, 
                                     Name,     
                                     RecurrenceDayOfMonth, 
                                     RecurrenceMonthOfYear
                              FROM Holiday])
        {
            String keyStr = holiday.RecurrenceDayOfMonth + holiday.RecurrenceMonthOfYear;
            lstHolidays.add(keyStr);
        }
        return lstHolidays;
    }

    public static Id getOrgWideEmailAddress(){
        OrgWideEmailAddress orgWideEmailAdd = [ SELECT Id
                                                FROM OrgWideEmailAddress
                                                WHERE Address = 'conversions@capitecbank.co.za' LIMIT 1];
        
        if(orgWideEmailAdd != null){
            return orgWideEmailAdd.Id;
        }
        else{
            return null;
        }
    }

    @AuraEnabled
    public static Boolean caseSubmission(Id caseId, List<Debit_Order__c> lstDOs){
        Boolean closeCase = true;
        
        try {
            for(Debit_Order__c debitOrder : lstDOs){
                if(debitOrder.Debit_Order_Initiator__r.Preferred_Comms__c != 'Client to Switch'){
                    closeCase = false;
                }
            }

            if(closeCase){
                publishCommsEvent(caseId);
            }
            else{
                updateCaseStatus(caseId, 'Submitted');
            }

            return true;
        }
        catch(Exception e) {
            System.debug('##Error case submission:' + e.getMessage());
            return false;
        }
    }

    @AuraEnabled
    public static void updateCaseStatus(Id caseId, String status) {
        Case caseToUpdate = new Case(Id=caseId, Status=status);
        update caseToUpdate;
    }

    
    @AuraEnabled
    public static Boolean getUnclassifiedFiles(Id caseId) {
        Integer countRecords = [
            SELECT COUNT()
            FROM IC_DocumentRequestList__c
            WHERE Case__c = :caseId
            AND CON_Classified__c = false
        ];

        return countRecords > 0;
    }


    public static void publishCommsEvent(String caseId) {

        Conversion_Comms__e eventMsg = new Conversion_Comms__e(
            Case__c = caseId,
            Case_Status__c = 'Closed',
            EventName__c = 'Conversion Comms',
            Type__c = 'Client To Switch'

        );

        Database.SaveResult sr = EventBus.publish(eventMsg);

        if (!sr.isSuccess()) {
            throw new AuraHandledException('Error publishing event');
        }
        else{
            updateCaseStatus(caseId, 'Closed');
        }
    }

    @AuraEnabled
    public static Boolean updateDebitOrders(List<Debit_Order__c> lstDOs, String causeCode) {
        System.debug('##causeCode:' + causeCode);
        System.debug('##causeCode length:' + causeCode.length());

        if (lstDOs == null || lstDOs.isEmpty() || String.isBlank(causeCode)) {
            return false;
        }

        List<Debit_Order__c> lstDOsToUpdate = new List<Debit_Order__c>();

        for (Debit_Order__c debitOrder : lstDOs) {
            if (debitOrder.Id != null) {
                lstDOsToUpdate.add(new Debit_Order__c(
                    Id = debitOrder.Id,
                    Withdrawn_Cause_Code__c = causeCode,
                    Submitted_Cause_Code__c = null
                ));
            }
        }

        if (lstDOsToUpdate.isEmpty()) {
            return false;
        }

        try {
            update lstDOsToUpdate;
            return true;
        } catch (Exception e) {
            System.debug('##Error updating debit orders: ' + e.getMessage());
            return false;
        }
    }
}