backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FD Debit Order Switch</fullName>
                </value>
                <value>
                    <fullName>WS debit Order Switch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <fields>
        <fullName>DOI_Contact_Email__c</fullName>
        <label>DOI Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CB To Email</fullName>
                </value>
                <value>
                    <fullName>CB to Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Client to Switch</fullName>
                </value>
                <value>
                    <fullName>MFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Conversions_AnalyseDebitOrdersTest.cls
/**
 * @description       : Test class for Conversions_AnalyseDebitOrders.cls
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 01-27-2026
 * @last modified by  : Samiirah Aujub
**/
@IsTest
public with sharing class Conversions_AnalyseDebitOrdersTest {

    public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();


    @testSetup
    static void setupTestData() {
        Case testCase = new Case(Subject = 'Test Case',
                                 Status = 'In Progress',
                                 Origin = 'Branch',
                                 RecordTypeId = CONVERSIONS_RECORDID
                                );
        insert testCase;


        Debit_Order_Initiator__c initiator = new Debit_Order_Initiator__c(Name = 'Test Initiator',
                                                                          Preferred_Comms__c = 'CB To Email',
                                                                          DOI_Contact_Email__c = 'testDOI@Capitec.com'
                                                                         );
        insert initiator;

        Debit_Order__c immediateDO = new Debit_Order__c(Name = 'DO-001',
                                                       Amount__c = 100.0,
                                                       From_Account__c = '123456789',
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_Order_Initiator__c = initiator.Id,
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       Case__c = testCase.Id,
                                                       Category__c = 'WS debit Order Switch'
        );
        Debit_Order__c immediateDO2 = new Debit_Order__c(Name = 'DO-002',
                                                       Amount__c = 100.0,
                                                       From_Account__c = '123456789',
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_Order_Initiator__c = initiator.Id,
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       Case__c = testCase.Id,
                                                       Category__c = 'WS debit Order Switch'
        );


        Debit_Order__c futureDatedDO = new Debit_Order__c(Name = 'DO-003',
                                                         Amount__c = 100.0,
                                                         From_Account__c = '123456789',
                                                         To_Capitec_Account__c = '987654321',
                                                         Debit_Order_Initiator__c = initiator.Id,
                                                         Debit_OrderDate__c = Date.today(),
                                                         Submitted_Cause_Code__c = 'No Client Action',
                                                         Case__c = testCase.Id,
                                                         Category__c = 'FD Debit Order Switch',
                                                         Submission_Date__c = Date.today() + 20);

       
        List<Debit_Order__c> lstDOs = new List<Debit_Order__c>{ immediateDO,immediateDO2, futureDatedDO };
        insert lstDOs;
    }



     @IsTest
    static void test_generateEmailBodyForDebitOrders_withData() {
        
        Case testCase = [SELECT Id FROM Case WHERE Subject = 'Test Case' LIMIT 1];
        Conversions_AnalyseDebitOrders.debitOrderInput inputWrapper = new Conversions_AnalyseDebitOrders.debitOrderInput();
        inputWrapper.caseId = testCase.Id;

        List<Conversions_AnalyseDebitOrders.DebitOrderOutput> results = Conversions_AnalyseDebitOrders.generateEmailBodyForDebitOrders(new List<Conversions_AnalyseDebitOrders.debitOrderInput>{inputWrapper});

        

        Conversions_AnalyseDebitOrders.DebitOrderOutput output = results[0];

        System.assert(output.noActionDebitOrdersText.contains('Test Initiator'), 'Immediate DO should contain initiator name');
        System.assertEquals(1, results.size(), 'One result should be returned');
    }
}