backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <fields>
        <fullName>Preferred_Comms__c</fullName>
        <label>Preferred Comms</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CB To Email</fullName>
                </value>
                <value>
                    <fullName>CB to Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Client to Switch</fullName>
                </value>
                <value>
                    <fullName>MFT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/IC_DocumentRequestList__c.object
<CustomObject>
    <fields>
        <fullName>CON_Classified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Classified</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Capitec_DebitOrderControllerTest.cls
/**
 * @description       : Test class for Capitec_DebitOrderController.cls
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 03-09-2026
 * @last modified by  : Samiirah Aujub
**/
@isTest
private class Capitec_DebitOrderControllerTest {

    public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();


    @testSetup
    static void setupTestData() {
        Case testCase = new Case(Subject = 'Test Case',
                                 Status = 'In Progress',
                                 Origin = 'Branch',
                                 RecordTypeId = CONVERSIONS_RECORDID
                                );
        insert testCase;

        Conversion__c conversion = new Conversion__c(Case__c = testCase.Id,
                                                     Old_Account_Number__c = '111222333'
                                                     );
        insert conversion;

        Debit_Order_Initiator__c initiator = new Debit_Order_Initiator__c(Name = 'Test Initiator',
                                                                          Preferred_Comms__c = 'Client to Switch'
                                                                         );
        insert initiator;

        Debit_Order__c debitOrder = new Debit_Order__c(Name = 'DO-001',
                                                       Amount__c = 100.0,
                                                       From_Account__c = '123456789',
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_Order_Initiator__c = initiator.Id,
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       Case__c = testCase.Id
        );
        insert debitOrder;

        IC_DocumentRequestList__c doc = new IC_DocumentRequestList__c(Case__c = testCase.Id,
                                                                      CON_Classified__c = false
                                        );
        insert doc;

    }

    @isTest
    static void testGetDebitOrders() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        List <Debit_Order__c> lstDOs = [SELECT Id,
                                               Debit_Order_Initiator__r.Preferred_Comms__c
                                        FROM Debit_Order__c];

        Test.startTest();
            Boolean result = Capitec_DebitOrderController.caseSubmission(testCase.Id, lstDOs);
        Test.stopTest();

        System.assertEquals(true, result,'caseSubmission should return true for valid inputs');
    }

    @isTest
    static void testCaseSubmission() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
        Capitec_DebitOrderController.CaseWrapper result = Capitec_DebitOrderController.getCaseInfo(testCase.Id);
        Test.stopTest();

        System.assertEquals(testCase.Id, result.caseRecord.Id, 'Returned case should match input case');
    }

    @isTest
    static void testUpdateCaseStatus() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
       		Capitec_DebitOrderController.updateCaseStatus(testCase.Id, 'Confirmed');
        Test.stopTest();

        Case updatedCase = [SELECT Status FROM Case WHERE Id = :testCase.Id];
        System.assertEquals('Confirmed', updatedCase.Status, 'Status should be updated');
    }

     @isTest
    static void testgetDOIDetails() {
        Debit_Order_Initiator__c debitOrderInit = [SELECT Id FROM Debit_Order_Initiator__c LIMIT 1];

        Test.startTest();
            Debit_Order_Initiator__c fetchedDOI = Capitec_DebitOrderController.getDOIDetails(debitOrderInit.Id);
        Test.stopTest();

        System.assertEquals(debitOrderInit.Id, fetchedDOI.Id, 'Case status update should succeed');
    }

    @isTest
    static void testGetHolidays() {
        Test.startTest();
            List<String> holidays = Capitec_DebitOrderController.getHolidays();
        Test.stopTest();

        System.assert(!holidays.isEmpty(), 'Holidays list should not be empty');
    }

    @isTest
    static void testGetOrgWideEmailAddress() {
        Test.startTest();
            Id resultId = Capitec_DebitOrderController.getOrgWideEmailAddress();
        Test.stopTest();

        System.assertNotEquals(null, resultId, 'Method should return OrgWideEmailAddress Id');
    }

    @isTest
    static void testGetConversionRecord() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
            Conversion__c conv = Capitec_DebitOrderController.getConversionRecord(testCase.Id);
        Test.stopTest();

        System.assertNotEquals(null, conv, 'Conversion record should be returned');
        System.assertEquals('111222333',conv.Old_Account_Number__c,'Old account number should match');
    }

    @isTest
    static void testGetUnclassifiedFiles() {
        Case testCase = [SELECT Id FROM Case LIMIT 1];

        Test.startTest();
            Boolean result = Capitec_DebitOrderController.getUnclassifiedFiles(testCase.Id);
        Test.stopTest();

        System.assertEquals(true, result);

    }
}