backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Terminated</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Allocated Assessing</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Response</fullName>
                </value>
                <value>
                    <fullName>Awaiting External Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting for Internal Department Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Insurer Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Medical Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting OCI Insurer</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Adverse Media</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Reported</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Review Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Sign Off: Review Not Required</fullName>
                </value>
                <value>
                    <fullName>Claims Forum</fullName>
                </value>
                <value>
                    <fullName>Claims Management</fullName>
                </value>
                <value>
                    <fullName>Contact Client</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Declined (Closed)</fullName>
                </value>
                <value>
                    <fullName>Documents not received</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>EDD Requirements Failed</fullName>
                </value>
                <value>
                    <fullName>Escalated - Mandate approval</fullName>
                </value>
                <value>
                    <fullName>Evaluating Client Response</fullName>
                </value>
                <value>
                    <fullName>Finalised</fullName>
                </value>
                <value>
                    <fullName>Final Termination Notice Sent</fullName>
                </value>
                <value>
                    <fullName>Guardrisk Assessing</fullName>
                </value>
                <value>
                    <fullName>HB 48hrs SMS notice</fullName>
                    <label>Hard Block 48hrs SMS notice</label>
                </value>
                <value>
                    <fullName>Hard Block Applied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case_Closure_Reason__c</fullName>
        <label>Case Closure Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Branch indicate - Ignore request</fullName>
                </value>
                <value>
                    <fullName>Client Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>Client Did not agree to switch</fullName>
                </value>
                <value>
                    <fullName>Client will submit</fullName>
                </value>
                <value>
                    <fullName>Invalid - Agreement not setup</fullName>
                </value>
                <value>
                    <fullName>Invalid - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Invalid - No active debit orders</fullName>
                </value>
                <value>
                    <fullName>Invalid - Request for Savings Plan</fullName>
                </value>
                <value>
                    <fullName>Invalid Bank Statement Request</fullName>
                </value>
                <value>
                    <fullName>Invalid Payslip Request – Invalid Reference number/No Amount</fullName>
                </value>
                <value>
                    <fullName>Invalid Payslip Request – No Payslip attached</fullName>
                </value>
                <value>
                    <fullName>Invalid Request - Bank Statement Older than 3 months</fullName>
                </value>
                <value>
                    <fullName>Invalid SMS Request – Incomplete or Invalid Reference/no amount</fullName>
                </value>
                <value>
                    <fullName>Missing Bank Statement/No Comments</fullName>
                </value>
                <value>
                    <fullName>Refund Processed</fullName>
                </value>
                <value>
                    <fullName>No attachment/invalid attachment</fullName>
                </value>
                <value>
                    <fullName>Query not related to switch</fullName>
                </value>
                <value>
                    <fullName>Auto Close</fullName>
                </value>
                <value>
                    <fullName>Auto Close - No Client feedback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Conversions_SubStatusController.cls
/**
 * @description       : 
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 10-23-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Conversions_SubStatusController {
    
    @AuraEnabled(cacheable=true)
    public static Case getCaseInfo(Id caseId) {
        return [
            SELECT Id,
                   CaseNumber,
                   Status,
                   Sub_Status__c,
                   OwnerId,
                   Owner.Name
            FROM Case
            WHERE Id = :caseId
            LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Conversion__c getConversionInfo(Id caseId) {
        return [
            SELECT Id,
                   Case_Closure_Reason__c,
                   Case__c
            FROM Conversion__c
            WHERE Case__c = :caseId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static Boolean createTask(String subject, String description, Date dueDate, Id caseId, Id ownerId) {
        try {
            Task task = new Task();
            task.Subject = subject;
            task.Description = description;
            task.ActivityDate = dueDate;
            task.OwnerId = ownerId;
            task.WhatId = caseId;

            System.debug('##Creating task: ' + task);


            insert task;
            return true;
        } catch (Exception ex) {
            System.debug('##Error creating task: ' + ex.getMessage());
            return false;
        }
    }

}