backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Afrikaans</fullName>
                </value>
                <value>
                    <fullName>Sapedi</fullName>
                </value>
                <value>
                    <fullName>Setswana</fullName>
                </value>
                <value>
                    <fullName>Sesotho</fullName>
                </value>
                <value>
                    <fullName>siSwati</fullName>
                </value>
                <value>
                    <fullName>Tshivenda</fullName>
                </value>
                <value>
                    <fullName>Xitsonga</fullName>
                </value>
                <value>
                    <fullName>isiNdebele</fullName>
                </value>
                <value>
                    <fullName>isiXhosa</fullName>
                </value>
                <value>
                    <fullName>isiZulu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/DocumentChecklistItem.object
<CustomObject>
    <recordTypes>
        <fullName>Conversion</fullName>
        <active>true</active>
        <label>Conversion</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Conversions_DOSwitchCaseCreation_Test.cls
/**
 * @description       : 
 * @author            : Rajesh Yandrathi
 * @group             : Cebtral Conversions
 * @last modified on  : 03-10-2026
 * @last modified by  : Samiirah Aujub
**/
@IsTest
public class Conversions_DOSwitchCaseCreation_Test {

    public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();

    //Added by Samiirah Aujub
    @testSetup
    static void setupTestData() {
        Case testCase = new Case(Subject = 'Test Case',
                                 Status = 'In Progress',
                                 Origin = 'Branch',
                                 Claim_Number__c = '12345679',
                                 RecordTypeId = CONVERSIONS_RECORDID
                                );
        insert testCase;

        Conversion__c conversion = new Conversion__c(Case__c = testCase.Id,
                                                     Old_Account_Number__c = '111222333'
                                                     );
        insert conversion;
    }

    @IsTest
    static void testCreateCase_WithDebitOrdersAndDocuments() {

        Id caseRecordTypeId;
        Map<String, Schema.RecordTypeInfo> rtMap =
            Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName();

        if (rtMap.containsKey('Conversions')) {
            caseRecordTypeId = rtMap.get('Conversions').getRecordTypeId();
        } else {
            caseRecordTypeId =
                Schema.SObjectType.Case.getRecordTypeInfos()[0].getRecordTypeId();
        }

        Group queue;
        List<Group> queues = [
            SELECT Id
            FROM Group
            WHERE DeveloperName = 'Central_Conversions'
            AND Type = 'Queue'
            LIMIT 1
        ];

        if (queues.isEmpty()) {
            queue = new Group(
                Name = 'Central Conversions',
                DeveloperName = 'Central_Conversions',
                Type = 'Queue'
            );
            insert queue;
        } else {
            queue = queues[0];
        }

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.httpMethod = 'POST';
        req.requestUri = '/services/apexrest/createDebitOrderSwitchCase/v1';

        req.requestBody = Blob.valueOf(
            JSON.serialize(new Map<String, Object>{
                'cdCIF' => '55557777',
                'idNumber' => '8965743902345',
                'consultantCP' => 'CP12345',
                'complexity' => 'Complex',
                'preferredTime' => '10:00:00',
                'preferredLanguage' => 'English',
                'preferredContactMethod' => 'SMS',
                'comments' => 'Client needs all debit orders switched by month end',
                'oldAccount' => '62498924234',
                'oldBank' => 'HSBC',
                'oldBranchCode' => '587000',
                'origin' => 'Digital',
                'typeValue' => 'Debit Order Switch',
                'subject' => 'Debit Order Switch Request',
                'statusValue' => 'New',
                'priorityValue' => 'Medium',
                'switchRequestId' => '12345678',
                'recordTypeId' => caseRecordTypeId,
                'ownerId' => queue.Id,
                'debitOrders' => new List<Object>{
                    new Map<String, Object>{
                        'fromAccount' => '123456789',
                        'toCapitecAccount' => '85756847474646',
                        'amount' => 980.00,
                        'debitOrderDate' => '2025-06-15',
                        'name' => 'FNB-Rent',
                        'externalInitiatorId' => 'DOI-1001',
                        'externalInitiatorName' => 'FNB Payments',
                        'inclusions' => 'Rent, Insurance, Gym',
                        'category' => 'FD Debit Order Switch',
                        'submissionDate' => '2025-10-15'
                    }
                },
                'documents' => new List<Object>{
                    new Map<String, Object>{
                        'name' => 'ID Document',
                        'documentLink' => 'https://example.com/id.pdf',
                        'documentumId' => 'DOC-001',
                        'documentType' => 'Bank Statement'
                    }
                }
            })
        );

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Conversions_DebitOrderSwitchCaseCreation.ResponseWrapper response =
            Conversions_DebitOrderSwitchCaseCreation.createCase();
        Test.stopTest();

        System.assertEquals(true, response.success);
        System.assertNotEquals(null, response.caseId);

        Case cs = [
            SELECT Id, CaseNumber
            FROM Case
            WHERE Id = :response.caseId
        ];

        System.assertNotEquals(null, cs.CaseNumber);

        Conversion__c conv = [
            SELECT Id, Preferred_Language__c, Preferred_Contact_Method__c
            FROM Conversion__c
            WHERE Case__c = :cs.Id
            LIMIT 1
        ];

        System.assertEquals('English', conv.Preferred_Language__c);

        List<Debit_Order__c> dos = [
            SELECT Id
            FROM Debit_Order__c
            WHERE Case__c = :cs.Id
        ];

        System.assertEquals(1, dos.size());

        List<DocumentChecklistItem> docs = [
            SELECT Id
            FROM DocumentChecklistItem
            WHERE ParentRecordId = :cs.Id
        ];

        System.assertEquals(1, docs.size());
    }


    /**
    * @description Test method for getDuplicateCase
    * @author Samiirah Aujub | 02-04-2026 
    **/
    @IsTest
    static void testGetDuplicateCase() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.httpMethod = 'POST';
        req.requestUri = '/services/apexrest/createDebitOrderSwitchCase/v1';

        req.requestBody = Blob.valueOf( JSON.serialize(new Map<String, Object>{
                                        'cdCIF' => '55557777',
                                        'idNumber' => '8965743902345',
                                        'consultantCP' => 'CP12345',
                                        'complexity' => 'Complex',
                                        'preferredTime' => '10:00:00',
                                        'preferredLanguage' => 'English',
                                        'preferredContactMethod' => 'SMS',
                                        'comments' => 'Client needs all debit orders switched by month end',
                                        'oldAccount' => '62498924234',
                                        'oldBank' => 'HSBC',
                                        'oldBranchCode' => '587000',
                                        'origin' => 'Digital',
                                        'typeValue' => 'Debit Order Switch',
                                        'subject' => 'Debit Order Switch Request',
                                        'statusValue' => 'New',
                                        'priorityValue' => 'Medium',
                                        'switchRequestId' => '12345679',
                                        'recordTypeId' => CONVERSIONS_RECORDID,
                                        'ownerId' => null,
                                        'debitOrders' => new List<Object>{
                                            new Map<String, Object>{
                                                'fromAccount' => '123456789',
                                                'toCapitecAccount' => '85756847474646',
                                                'amount' => 980.00,
                                                'debitOrderDate' => '2025-06-15',
                                                'name' => 'FNB-Rent',
                                                'externalInitiatorId' => 'DOI-1001',
                                                'externalInitiatorName' => 'FNB Payments',
                                                'inclusions' => 'Rent, Insurance, Gym',
                                                'category' => 'FD Debit Order Switch',
                                                'submissionDate' => '2025-10-15'
                                            }
                                        },
                                        'documents' => new List<Object>{
                                            new Map<String, Object>{
                                                'name' => 'ID Document',
                                                'documentLink' => 'https://example.com/id.pdf',
                                                'documentumId' => 'DOC-001',
                                                'documentType' => 'Bank Statement'
                                            }
                                        }
                                    })
                                );

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Conversions_DebitOrderSwitchCaseCreation.ResponseWrapper response = Conversions_DebitOrderSwitchCaseCreation.createCase();
        Test.stopTest();

        System.assertEquals(false, response.success);
    }
}