backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Conversions</fullName>
        <active>true</active>
        <businessProcess>Conversions</businessProcess>
        <description>Record type for Debit Order Switch</description>
        <label>Conversions</label>
    </recordTypes>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Confirmation_Cause_Code__c</fullName>
        <label>Confirmation Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Closed</fullName>
                </value>
                <value>
                    <fullName>Account Handover/Debt Review</fullName>
                </value>
                <value>
                    <fullName>Action Required From Client</fullName>
                </value>
                <value>
                    <fullName>Bank Details Already Updated</fullName>
                </value>
                <value>
                    <fullName>Cash payer customer</fullName>
                </value>
                <value>
                    <fullName>Client Not Contactable</fullName>
                </value>
                <value>
                    <fullName>Client Not Interested</fullName>
                </value>
                <value>
                    <fullName>Client to Contact DOI</fullName>
                </value>
                <value>
                    <fullName>Confirmation via SMS Required</fullName>
                </value>
                <value>
                    <fullName>Debit Order/Policy Cancelled</fullName>
                </value>
                <value>
                    <fullName>Details Not Found/Invalid Details</fullName>
                </value>
                <value>
                    <fullName>No active debit orders</fullName>
                </value>
                <value>
                    <fullName>Paid up</fullName>
                </value>
                <value>
                    <fullName>Policy lapsed/frozen</fullName>
                </value>
                <value>
                    <fullName>Successfully Confirmed</fullName>
                </value>
                <value>
                    <fullName>Confirmation via email required</fullName>
                    <isActive>false</isActive>
                    <label>Confirmation via email required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Capitec_ConversionVerifyDebitOrdersTest.cls
/**
 * @description       : Test class for Capitec_ConversionVerifyDebitOrders.cls
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 01-27-2026
 * @last modified by  : Samiirah Aujub
**/
@isTest
public with sharing class Capitec_ConversionVerifyDebitOrdersTest {
    public static Id CONVERSIONS_RECORDID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Conversions').getRecordTypeId();

    @TestSetup
    static void setupTestData() {
         Case testCaseNoResponse = new Case(Subject = 'Case related to DOs with no reponses',
                                            Status = 'In Progress',
                                            Origin = 'Branch',
                                            RecordTypeId = CONVERSIONS_RECORDID
                                        );
                                        
        Case testCaseResponse = new Case(Subject = 'Case related to DOs with responses',
                                         Status = 'In Progress',
                                         Origin = 'Branch',
                                         RecordTypeId = CONVERSIONS_RECORDID
                                        );

        insert new List<Case>{ testCaseNoResponse, testCaseResponse };

        Debit_Order__c debitOrder = new Debit_Order__c(Name = 'DO-001',
                                                       Amount__c = 100.0,
                                                       From_Account__c = '123456789',
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       Case__c = testCaseNoResponse.Id
                                                     );
        Debit_Order__c debitOrder2 = new Debit_Order__c(Name = 'DO-001',
                                                       Amount__c = 100.0,
                                                       From_Account__c = '123455789',
                                                       To_Capitec_Account__c = '987654321',
                                                       Debit_OrderDate__c = Date.today(),
                                                       Submitted_Cause_Code__c = 'Client to Action',
                                                       Case__c = testCaseNoResponse.Id
        );

        Debit_Order__c debitOrderConfirmed = new Debit_Order__c(Name = 'DO-002',
                                                                Amount__c = 100.0,
                                                                From_Account__c = '123456789',
                                                                To_Capitec_Account__c = '987654321',
                                                                Debit_OrderDate__c = Date.today(),
                                                                Confirmation_Cause_Code__c = '	Client to Contact DOI',
                                                                Case__c = testCaseResponse.Id
                                                                );
        Debit_Order__c debitOrderConfirmed2 = new Debit_Order__c(Name = 'DO-002',
                                                                Amount__c = 100.0,
                                                                From_Account__c = '123456789',
                                                                To_Capitec_Account__c = '987654321',
                                                                Debit_OrderDate__c = Date.today(),
                                                                Confirmation_Cause_Code__c = '	Client to Contact DOI',
                                                                Case__c = testCaseResponse.Id
                                                                );
        
        

        
        insert new List<Debit_Order__c>{debitOrder,debitOrder2, debitOrderConfirmed,debitOrderConfirmed2};
        
    }


    public static List<Capitec_ConversionVerifyDebitOrders.responseWrapper> callAnalyse(Id caseId) {
        Capitec_ConversionVerifyDebitOrders.requestWrapper req = new Capitec_ConversionVerifyDebitOrders.requestWrapper();
        req.caseId = caseId;
        return Capitec_ConversionVerifyDebitOrders.analyseDebitOrders(new List<Capitec_ConversionVerifyDebitOrders.requestWrapper>{ req });
    }
    
    @IsTest
    public static void testDebitOrderResponse() {
        Case caseRecord = [SELECT Id FROM Case WHERE Subject = 'Case related to DOs with responses'];

        List<Capitec_ConversionVerifyDebitOrders.responseWrapper> result = callAnalyse(caseRecord.Id);
        Assert.isTrue(result[0].result, 'All DOs have a confirmation cause code. Case Auto Close');
    }
    
    @IsTest
    public static void testDebitOrderNoResponse() {
         Case caseRecord = [SELECT Id, Subject FROM Case WHERE Subject = 'Case related to DOs with no reponses'];

         System.debug('##testDebitOrderNoResponse caseRecord fetched:' + caseRecord);

        List<Capitec_ConversionVerifyDebitOrders.responseWrapper> result = callAnalyse(caseRecord.Id);
        Assert.isFalse(result[0].result, 'At least one Debit_Order missing Confirmation_Cause_Code . Case remain open');
    }
}