backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Bank_Name__c</fullName>
        <label>Bank Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20TWENTY</fullName>
                </value>
                <value>
                    <fullName>ABN AMRO BANK</fullName>
                </value>
                <value>
                    <fullName>ABSA BANK</fullName>
                </value>
                <value>
                    <fullName>ACCESS BANK (SOUTH AFRICA) LTD</fullName>
                </value>
                <value>
                    <fullName>AFRICAN BANK</fullName>
                </value>
                <value>
                    <fullName>ALBARAKA BANK</fullName>
                </value>
                <value>
                    <fullName>BANK WINDHOEK</fullName>
                </value>
                <value>
                    <fullName>BANK ZERO MUTUAL BANK</fullName>
                </value>
                <value>
                    <fullName>BIDVEST BANK</fullName>
                </value>
                <value>
                    <fullName>BNP PARIBAS SA SOUTH AFRICA</fullName>
                </value>
                <value>
                    <fullName>CAPITEC BANK</fullName>
                </value>
                <value>
                    <fullName>CITI BANK</fullName>
                </value>
                <value>
                    <fullName>DISCOVERY BANK</fullName>
                </value>
                <value>
                    <fullName>FBC FIDELITY BANK</fullName>
                </value>
                <value>
                    <fullName>FINBOND MUTUAL BANK</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK LESOTHO</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK NAMIBIA</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK SWAZILAND</fullName>
                </value>
                <value>
                    <fullName>GRINDROD BANK</fullName>
                </value>
                <value>
                    <fullName>HABIB OVERSEAS BANK</fullName>
                </value>
                <value>
                    <fullName>HBZ BANK</fullName>
                </value>
                <value>
                    <fullName>HSBC</fullName>
                </value>
                <value>
                    <fullName>INVESTEC BANK</fullName>
                </value>
                <value>
                    <fullName>ITHALA ABSA</fullName>
                </value>
                <value>
                    <fullName>JP MORGAN CHASE BANK</fullName>
                </value>
                <value>
                    <fullName>MEEG BANK</fullName>
                </value>
                <value>
                    <fullName>MERCANTILE BANK</fullName>
                </value>
                <value>
                    <fullName>MTN BANKING</fullName>
                </value>
                <value>
                    <fullName>NEDBANK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Old_Branch_Code__c</fullName>
        <label>Branch Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>170305</fullName>
                </value>
                <value>
                    <fullName>198765</fullName>
                </value>
                <value>
                    <fullName>250655</fullName>
                </value>
                <value>
                    <fullName>255050</fullName>
                </value>
                <value>
                    <fullName>280061</fullName>
                </value>
                <value>
                    <fullName>280164</fullName>
                </value>
                <value>
                    <fullName>282672</fullName>
                </value>
                <value>
                    <fullName>350005</fullName>
                </value>
                <value>
                    <fullName>400001</fullName>
                </value>
                <value>
                    <fullName>410105</fullName>
                </value>
                <value>
                    <fullName>430000</fullName>
                </value>
                <value>
                    <fullName>431010</fullName>
                </value>
                <value>
                    <fullName>432000</fullName>
                </value>
                <value>
                    <fullName>450105</fullName>
                </value>
                <value>
                    <fullName>460005</fullName>
                </value>
                <value>
                    <fullName>462005</fullName>
                </value>
                <value>
                    <fullName>470010</fullName>
                </value>
                <value>
                    <fullName>490991</fullName>
                </value>
                <value>
                    <fullName>51001</fullName>
                </value>
                <value>
                    <fullName>580105</fullName>
                </value>
                <value>
                    <fullName>584000</fullName>
                </value>
                <value>
                    <fullName>585001</fullName>
                </value>
                <value>
                    <fullName>587000</fullName>
                </value>
                <value>
                    <fullName>588000</fullName>
                </value>
                <value>
                    <fullName>589000</fullName>
                </value>
                <value>
                    <fullName>632005</fullName>
                </value>
                <value>
                    <fullName>634721</fullName>
                </value>
                <value>
                    <fullName>678910</fullName>
                </value>
                <value>
                    <fullName>679000</fullName>
                </value>
                <value>
                    <fullName>683000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Capitec_ConversionVFController.cls
/**
 * @description       : 
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 09-09-2025
 * @last modified by  : Samiirah.A@bsky.co.za
**/
public with sharing class Capitec_ConversionVFController {

    public String ClientName { get; private set; }
    public String IdNumber { get; private set; }
    public String CellNumber { get; private set; }

    public String OldBankName { get; private set; }
    public String OldBranchCode { get; private set; }
    public String OldAccountNumber { get; private set; }

    public String NewBankName { get; private set; }
    public String NewBranchCode { get; private set; }
    public String NewAccountType { get; private set; }
    public String NewAccountNumber { get; private set; }

    public String InitiatorName { get; private set; }
    public String ReferenceNumber { get; private set; }
    public String Frequency { get; private set; }
    public Decimal Amount { get; private set; }

    public Capitec_ConversionVFController(ApexPages.StandardController std) {
        Id caseId = (Id) std.getId();

        Conversion__c conversionRecord = [SELECT Id,
                                                  Old_Account_Number__c,
                                                  Old_Bank_Name__c,
                                                  Old_Branch_Code__c
                                            FROM Conversion__c
                                            WHERE Case__c =:caseId
                                            LIMIT 1
                                         ];

        Debit_Order__c doRec = [ SELECT Id,
                                        Name,
                                        Amount__c,
                                        To_Capitec_Account__c,
                                        Case__r.Account.Name,
                                        Case__r.Account.Identity_Number__c,
                                        Case__r.Account.PersonMobilePhone,
                                        Debit_Order_Initiator__r.Name
                                    FROM Debit_Order__c
                                    WHERE Case__c = :caseId
                                    LIMIT 1
                                ];

        //ClientName       = doRec.Case__r.Account.Name;
        //IdNumber         = doRec.Account.Identity_Number__c;
        //CellNumber       = doRec.Account.PersonMobilePhone;

        OldBankName      = conversionRecord.Old_Bank_Name__c;
        OldBranchCode    = conversionRecord.Old_Branch_Code__c;
        OldAccountNumber = conversionRecord.Old_Account_Number__c;

        NewAccountNumber = doRec.To_Capitec_Account__c;

        InitiatorName    = doRec.Debit_Order_Initiator__r.Name;
        ReferenceNumber  = doRec.Name;
        Amount           = doRec.Amount__c;
    }
}