backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manual_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to define if the case was created manually</description>
        <label>Manual Case?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Old_Account_Number__c</fullName>
        <label>Account Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Bank_Name__c</fullName>
        <label>Bank Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20TWENTY</fullName>
                </value>
                <value>
                    <fullName>ABN AMRO BANK</fullName>
                </value>
                <value>
                    <fullName>ABSA BANK</fullName>
                </value>
                <value>
                    <fullName>ACCESS BANK (SOUTH AFRICA) LTD</fullName>
                </value>
                <value>
                    <fullName>AFRICAN BANK</fullName>
                </value>
                <value>
                    <fullName>ALBARAKA BANK</fullName>
                </value>
                <value>
                    <fullName>BANK WINDHOEK</fullName>
                </value>
                <value>
                    <fullName>BANK ZERO MUTUAL BANK</fullName>
                </value>
                <value>
                    <fullName>BIDVEST BANK</fullName>
                </value>
                <value>
                    <fullName>BNP PARIBAS SA SOUTH AFRICA</fullName>
                </value>
                <value>
                    <fullName>CAPITEC BANK</fullName>
                </value>
                <value>
                    <fullName>CITI BANK</fullName>
                </value>
                <value>
                    <fullName>DISCOVERY BANK</fullName>
                </value>
                <value>
                    <fullName>FBC FIDELITY BANK</fullName>
                </value>
                <value>
                    <fullName>FINBOND MUTUAL BANK</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK LESOTHO</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK NAMIBIA</fullName>
                </value>
                <value>
                    <fullName>FIRST NATIONAL BANK SWAZILAND</fullName>
                </value>
                <value>
                    <fullName>GRINDROD BANK</fullName>
                </value>
                <value>
                    <fullName>HABIB OVERSEAS BANK</fullName>
                </value>
                <value>
                    <fullName>HBZ BANK</fullName>
                </value>
                <value>
                    <fullName>HSBC</fullName>
                </value>
                <value>
                    <fullName>INVESTEC BANK</fullName>
                </value>
                <value>
                    <fullName>ITHALA ABSA</fullName>
                </value>
                <value>
                    <fullName>JP MORGAN CHASE BANK</fullName>
                </value>
                <value>
                    <fullName>MEEG BANK</fullName>
                </value>
                <value>
                    <fullName>MERCANTILE BANK</fullName>
                </value>
                <value>
                    <fullName>MTN BANKING</fullName>
                </value>
                <value>
                    <fullName>NEDBANK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Old_Branch_Code__c</fullName>
        <label>Branch Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>170305</fullName>
                </value>
                <value>
                    <fullName>198765</fullName>
                </value>
                <value>
                    <fullName>250655</fullName>
                </value>
                <value>
                    <fullName>255050</fullName>
                </value>
                <value>
                    <fullName>280061</fullName>
                </value>
                <value>
                    <fullName>280164</fullName>
                </value>
                <value>
                    <fullName>282672</fullName>
                </value>
                <value>
                    <fullName>350005</fullName>
                </value>
                <value>
                    <fullName>400001</fullName>
                </value>
                <value>
                    <fullName>410105</fullName>
                </value>
                <value>
                    <fullName>430000</fullName>
                </value>
                <value>
                    <fullName>431010</fullName>
                </value>
                <value>
                    <fullName>432000</fullName>
                </value>
                <value>
                    <fullName>450105</fullName>
                </value>
                <value>
                    <fullName>460005</fullName>
                </value>
                <value>
                    <fullName>462005</fullName>
                </value>
                <value>
                    <fullName>470010</fullName>
                </value>
                <value>
                    <fullName>490991</fullName>
                </value>
                <value>
                    <fullName>51001</fullName>
                </value>
                <value>
                    <fullName>580105</fullName>
                </value>
                <value>
                    <fullName>584000</fullName>
                </value>
                <value>
                    <fullName>585001</fullName>
                </value>
                <value>
                    <fullName>587000</fullName>
                </value>
                <value>
                    <fullName>588000</fullName>
                </value>
                <value>
                    <fullName>589000</fullName>
                </value>
                <value>
                    <fullName>632005</fullName>
                </value>
                <value>
                    <fullName>634721</fullName>
                </value>
                <value>
                    <fullName>678910</fullName>
                </value>
                <value>
                    <fullName>679000</fullName>
                </value>
                <value>
                    <fullName>683000</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Time__c</fullName>
        <label>Preferred Contact Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Afrikaans</fullName>
                </value>
                <value>
                    <fullName>Sapedi</fullName>
                </value>
                <value>
                    <fullName>Setswana</fullName>
                </value>
                <value>
                    <fullName>Sesotho</fullName>
                </value>
                <value>
                    <fullName>siSwati</fullName>
                </value>
                <value>
                    <fullName>Tshivenda</fullName>
                </value>
                <value>
                    <fullName>Xitsonga</fullName>
                </value>
                <value>
                    <fullName>isiNdebele</fullName>
                </value>
                <value>
                    <fullName>isiXhosa</fullName>
                </value>
                <value>
                    <fullName>isiZulu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FD Debit Order Switch</fullName>
                </value>
                <value>
                    <fullName>WS debit Order Switch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_OrderDate__c</fullName>
        <label>Debit Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Debit_Order_Initiator_ID__c</fullName>
        <label>External Debit Order Initiator ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Debit_Order_Initiator_Name__c</fullName>
        <label>External Debit Order Initiator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Account__c</fullName>
        <label>From Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Capitec_Account__c</fullName>
        <label>To Capitec Account</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/DocumentChecklistItem.object
<CustomObject>
    <fields>
        <fullName>CON_Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank Statement</fullName>
                </value>
                <value>
                    <fullName>Agreement Form</fullName>
                </value>
                <value>
                    <fullName>Switching Template</fullName>
                </value>
                <value>
                    <fullName>ID/Passport</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>AnotherDoc</fullName>
                    <isActive>false</isActive>
                    <label>AnotherDoc</label>
                </value>
                <value>
                    <fullName>Bank Statement(s)</fullName>
                    <isActive>false</isActive>
                    <label>Bank Statement(s)</label>
                </value>
                <value>
                    <fullName>Extracted doc</fullName>
                    <isActive>false</isActive>
                    <label>Extracted doc</label>
                </value>
                <value>
                    <fullName>Extraction form</fullName>
                    <isActive>false</isActive>
                    <label>Extraction form</label>
                </value>
                <value>
                    <fullName>OCR Extraction</fullName>
                    <isActive>false</isActive>
                    <label>OCR Extraction</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>test</fullName>
                    <isActive>false</isActive>
                    <label>test</label>
                </value>
                <value>
                    <fullName>testType</fullName>
                    <isActive>false</isActive>
                    <label>testType</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Conversions_DebitOrderAsyncProcessor.cls
/**
 * @description       : 
 * @author            : Samiirah Aujub
 * @group             : 
 * @last modified on  : 03-23-2026
 * @last modified by  : Samiirah Aujub
**/
global with sharing class Conversions_DebitOrderAsyncProcessor
    implements Queueable, Database.AllowsCallouts {

    private Id caseId;
    private Conversions_DebitOrderSwitchCaseCreation.RequestWrapper input;

    global Conversions_DebitOrderAsyncProcessor(
        Id caseId,
        Conversions_DebitOrderSwitchCaseCreation.RequestWrapper input
    ) {
        this.caseId = caseId;
        this.input  = input;
    }

    global void execute(QueueableContext context) {

        Conversion__c conv = new Conversion__c(
            Case__c                     = caseId,
            Preferred_Contact_Time__c   = input.preferredTime,
            Preferred_Language__c       = input.preferredLanguage,
            Preferred_Contact_Method__c = input.preferredContactMethod,
            Additional_Comments__c      = input.comments,
            Old_Account_Number__c       = input.oldAccount,
            Old_Bank_Name__c            = input.oldBank,
            Old_Branch_Code__c          = input.oldBranchCode,
            Manual_Case__c              = input.manualCase == true //COCONV-2417

        );
        insert conv;

        if (input.debitOrders != null && !input.debitOrders.isEmpty()) {
            List<Debit_Order__c> dos = new List<Debit_Order__c>();

            for (Conversions_DebitOrderSwitchCaseCreation.DebitOrderWrapper d : input.debitOrders) {
                dos.add(new Debit_Order__c(
                    Case__c                                = caseId,
                    From_Account__c                        = d.fromAccount,
                    To_Capitec_Account__c                  = d.toCapitecAccount,
                    Amount__c                              = d.amount,
                    Debit_OrderDate__c                     = d.debitOrderDate,
                    Name                                   = d.name,
                    External_Debit_Order_Initiator_ID__c   = d.externalInitiatorId,
                    External_Debit_Order_Initiator_Name__c = d.externalInitiatorName,
                    Category__c                            = d.category,
                    Submission_Date__c                     = d.submissionDate
                ));
            }

            if (!dos.isEmpty()) {
                insert dos;
            }
        }

        if (input.documents != null && !input.documents.isEmpty()) {
            List<DocumentChecklistItem> docItems = new List<DocumentChecklistItem>();

            for (Conversions_DebitOrderSwitchCaseCreation.DocumentChecklistItemWrapper doc : input.documents) {
                docItems.add(new DocumentChecklistItem(
                    Name                 = doc.name,
                    ParentRecordId       = caseId,
                    Document_Link__c     = doc.documentLink,
                    IC_ExternalContentDocumentId__c  = doc.documentumId,
                    CON_Document_Type__c = doc.documentType
                ));
            }

            if (!docItems.isEmpty()) {
                insert docItems;
            }
        }
    }
}