backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Conversion__c.object
<CustomObject>
    <description>This object is used to store all the information related to conversion cases [Debit Order Switch]</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>The master case created for conversion request [Debit Order Switch</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Conversion</relationshipLabel>
        <relationshipName>Conversion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Time__c</fullName>
        <label>Preferred Contact Time</label>
        <type>Time</type>
    </fields>
    <label>Conversion</label>
    <nameField>
        <label>Conversion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DO_Issue__c</fullName>
        <label>DO Issue</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reference number unclear</fullName>
                </value>
                <value>
                    <fullName>Incomplete reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid Reference number</fullName>
                </value>
                <value>
                    <fullName>Invalid or incomplete debit order info</fullName>
                </value>
                <value>
                    <fullName>No amount provided</fullName>
                </value>
                <value>
                    <fullName>Client unreachable/ no response</fullName>
                </value>
                <value>
                    <fullName>Requested Debit order does not reflect on the statement</fullName>
                </value>
                <value>
                    <fullName>DOA missing</fullName>
                </value>
                <value>
                    <fullName>DOA invalid</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Debit_Order_Issue__c</fullName>
        <label>Other Debit Order Issue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Conversions_EmailTemplatesController.cls
/**
 * @description       : Apex Controller For Email Templates[Manual]
 * @author            : Samiirah.A@bsky.co.za
 * @group             : 
 * @last modified on  : 01-28-2026
 * @last modified by  : Samiirah Aujub
**/
public with sharing class Conversions_EmailTemplatesController {
    public Id caseRecordId { get; set; }
    public String emailThreadId { get; private set; }


    public Case getCaseRecord() {
        if (caseRecordId != null) {
            Case caseRecord = [
                SELECT Id, 
                       Account.Name, 
                       Account.PersonMobilePhone,
                       ID_Number__c, 
                       CreatedDate, 
                       Owner.Name, 
                       Branch_Code__c
                FROM Case
                WHERE Id = :caseRecordId
                LIMIT 1
            ];

            emailThreadId = EmailMessages.getFormattedThreadingToken(caseRecordId);
            return caseRecord;
        }
        return null;
    }

    public Conversion__c getConversion() {
        if (caseRecordId != null) {
            List<Conversion__c> convs = [
                SELECT Preferred_Contact_Time__c
                FROM Conversion__c
                WHERE Case__c = :caseRecordId
                LIMIT 1
            ];
            return convs.isEmpty() ? null : convs[0];
        }
        return null;
    }

    private List<Debit_Order__c> getDebitOrdersWithIssues() {
        if (caseRecordId == null) return new List<Debit_Order__c>();

        List<Debit_Order__c> lstDebitOrders = new List<Debit_Order__c>();
        lstDebitOrders = [SELECT Id,
                                 Name,
                                 DO_Issue__c,
                                 Other_Debit_Order_Issue__c,
                                 Debit_Order_Initiator__r.Name
                           FROM Debit_Order__c
                           WHERE Case__c = :caseRecordId
                           AND DO_Issue__c != null
                           ORDER BY CreatedDate ASC
                        ];

        return lstDebitOrders;
    }

    public Boolean getHasIssues() {
        return !getDebitOrdersWithIssues().isEmpty();
    }

    public List<String> getDebitOrderIssueLines() {
        List<String> lines = new List<String>();

        for (Debit_Order__c debitOrder : getDebitOrdersWithIssues()) {
            String doiName = (debitOrder.Debit_Order_Initiator__r != null && !String.isBlank(debitOrder.Debit_Order_Initiator__r.Name))
                            ? debitOrder.Debit_Order_Initiator__r.Name
                            : 'N/A';

            String refNo = String.isBlank(debitOrder.Name) ? 'N/A' : debitOrder.Name;


            String issueSummary = '';
            if (!String.isBlank(debitOrder.DO_Issue__c)) {
                issueSummary = debitOrder.DO_Issue__c.replace(';', ', ');
            }

            if (!String.isBlank(debitOrder.DO_Issue__c)
                && debitOrder.DO_Issue__c.contains('Other')
                && !String.isBlank(debitOrder.Other_Debit_Order_Issue__c)) {

                issueSummary += ' - ' + debitOrder.Other_Debit_Order_Issue__c;
            }

            if (String.isBlank(issueSummary)) {
                issueSummary = 'N/A';
            }
            lines.add(doiName + ' , Ref: ' + refNo + ' , Issue: ' + issueSummary);
        }
        return lines;
    }
}