backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order__c.object
<CustomObject>
    <description>This object represent the debit order detail related to a Debit Order Switch for the Conversion team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case Record Id related to the Debit Order Detail record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Debit_Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FD Debit Order Switch</fullName>
                </value>
                <value>
                    <fullName>WS debit Order Switch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Debit_Order_Initiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOI Name</label>
        <referenceTo>Debit_Order_Initiator__c</referenceTo>
        <relationshipLabel>Debit Orders</relationshipLabel>
        <relationshipName>Debit_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_Cause_Code__c</fullName>
        <label>Submitted Cause Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client to Action</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                    <default>true</default>
                    <label>No Client Action</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Debit Order</label>
    <nameField>
        <label>DO Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/objects/Debit_Order_Initiator__c.object
<CustomObject>
    <label>Debit Order Initiator</label>
    <nameField>
        <label>DOI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debit Order Initiators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

backup/masterpackage-retrieve/unpackaged/unpackaged/classes/Conversions_AnalyseDebitOrders.cls
/**
 * @description       : Prepare list of Immediate and Future Dated Debit Orders
 * @author            : Samiirah.A@bsky.co.za
 * @group             : Conversions
 * @last modified on  : 09-22-2025
 * @last modified by  : Samiirah.A@bsky.co.za
**/
public with sharing class Conversions_AnalyseDebitOrders {

    @InvocableMethod(label='Segregate Debit Orders')
    public static List<DebitOrderOutput> generateEmailBodyForDebitOrders(List<debitOrderInput> requests) {
        String noActionDOStr = '';
        String clientActionStr = '';
         List<DebitOrderOutput> lstOutputs = new List<DebitOrderOutput>();

        debitOrderInput request = requests[0];

        if(request != null){
            List<Debit_Order__c> lstDebitOrders = [SELECT Id,
                                                    Amount__c,
                                                    Category__c,
                                                    Submitted_Cause_Code__c,
                                                    Debit_Order_Initiator__r.Name
                                                FROM Debit_Order__c 
                                                WHERE Case__c = :request.caseId ];

            if(!lstDebitOrders.isEmpty()){
                Map<String,List<Debit_Order__c>> mapDebitOrderTypeToDOs = segregateDOs(lstDebitOrders);

                if(mapDebitOrderTypeToDOs.containsKey('No Client Action')){
                        noActionDOStr += '<ol>';
                        for(Debit_Order__c debitOrder : mapDebitOrderTypeToDOs.get('No Client Action')){
                            noActionDOStr += '<li>';
                            noActionDOStr +=  debitOrder.Debit_Order_Initiator__r.Name + ' ';
                            noActionDOStr +=  'R' + debitOrder.Amount__c + '</li>';
                        }
                        noActionDOStr += '</ol>';
                }


                if(mapDebitOrderTypeToDOs.containsKey('Client to Action')){
                    clientActionStr += '<ol>';
                    for(Debit_Order__c debitOrder : mapDebitOrderTypeToDOs.get('Client to Action')){
                        clientActionStr += '<li>';
                        clientActionStr +=  debitOrder.Debit_Order_Initiator__r.Name + ' ';
                        clientActionStr +=  'R' + debitOrder.Amount__c + '</li>';
                    }
                    clientActionStr += '</ol>';
                }
            }
        }

        DebitOrderOutput output = new DebitOrderOutput();
        output.noActionDebitOrdersText = noActionDOStr;
        output.clientActionDebitOrdersText = clientActionStr;

        lstOutputs.add(output);

        return lstOutputs;
    }

    public static Map<String, List<Debit_Order__c>> segregateDOs(List<Debit_Order__c> lstDOs){
        Map<String, List<Debit_Order__c>> mapDebitOrderTypeToDOs = new Map<String, List<Debit_Order__c>>();

        for(Debit_Order__c debitOrder : lstDOs){
            if(mapDebitOrderTypeToDOs.containsKey(debitOrder.Submitted_Cause_Code__c)){
                mapDebitOrderTypeToDOs.get(debitOrder.Submitted_Cause_Code__c).add(debitOrder);
            }else{
                mapDebitOrderTypeToDOs.put(debitOrder.Submitted_Cause_Code__c, new List<Debit_Order__c>{debitOrder});
            }
        }
        return mapDebitOrderTypeToDOs;
    }
     public class debitOrderInput {
        @InvocableVariable(required=true)
        public Id caseId;
    }

    public class debitOrderOutput {
        @InvocableVariable
        public String noActionDebitOrdersText;

        @InvocableVariable
        public String clientActionDebitOrdersText;
    }
}